---
  - name: checking java
    command: java -version
    register: java_installed
    ignore_errors: yes
  - name: install java
    yum:
      name: openjdk-11-jdk
      state: present
    when: java_installed.failed
