---
  - name: download tomcat
    get_url:
      url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.91/bin/apache-tomcat-9.0.91.tar.gz"
      dest: /tmp/apache-tomcat-9.0.91.tar.gz
  - name: extract tomcat
    unarchieve:
      src: /tmp/apache-tomcat-9.0.91.tar.gz
      dest: /opt/
      remote_src: yes
  - name: create a symbolic link to tomcat
    file:
      src: /opt/apache-tomcat-9.0.91.tar.gz
      dest: /opt/tomcat
      state: link
  - name: tomcat service script
    template:
      src: tomcat.service.j2
      dest: /etc/systemd/system/tomcat.service
  - name: reload systemd
    command: systemctl deamon-reload
  -name: start and enable tomcat
  systemd:
    name: tomcat
    state: started
    enabled: yes
