---
  - name: download tomcat
    get_url:
      url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.91/bin/apache-tomcat-9.0.91.tar.gz"
      dest: /tmp/apache-tomcat-9.0.91.tar.gz
  - name: extract tomcat
    unarchive:
      src: /tmp/apache-tomcat-9.0.91.tar.gz
      dest: /opt/
      remote_src: yes
  - name: Check if the Tomcat folder already contains files
    stat:
      path: /opt/tomcat/bin
    register: tomcat_bin
  - name: Move all contents to the Tomcat folder
    command: mv /opt/apache-tomcat-9.0.91/ /opt/tomcat/
    when: not tomcat_bin.stat.exists
  - name: tomcat service script
    template:
      src: tomcat.service.j2
      dest: /etc/systemd/system/tomcat.service
  - name: reload systemd
    command: systemctl daemon-reload
  - name: start and enable tomcat
    shell: nohup /opt/tomcat/bin/startup.sh 
